from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('infor/', information, name="information"),
    path('myshop/', myshop, name="myshop"),
    path('mongs/', mongs, name="mongs"),
    path('record/', record, name="record"),
    path('test/', test, name="test"),
    path('test2/', test2, name="test2"),
    path('test3/', test3, name="test3"),
    path('result/', result, name="result"),
    path('mymong/', mymong, name="mymong"),
    path('chid/', chid, name="chid"),
    path('chpw/', chpw, name="chpw"),
    path('result_ty/', result_ty, name="result_ty"),
    path('result_te/', result_te, name="result_te"),
    path('result_sy/', result_sy, name="result_sy"),
    path('result_se/', result_se, name="result_se"),
    path('birth_load/', birth_load, name="birth_load"),
    path('birth_l_te/', birth_l_te, name="birth_l_te"),
    path('birth_l_sy/', birth_l_sy, name="birth_l_sy"),
    path('birth_l_se/', birth_l_se, name="birth_l_se"),
    path('birth_ty/', birth_ty, name="birth_ty"),
    path('birth_te/', birth_te, name="birth_te"),
    path('birth_sy/', birth_sy, name="birth_sy"),
    path('birth_se/', birth_se, name="birth_se"),
    path('info_ty/', info_ty, name="info_ty"),
    path('info_te/', info_te, name="info_te"),
    path('info_sy/', info_sy, name="info_sy"),
    path('info_se/', info_se, name="info_se"),
    path('index/', index, name="index"),
    path('create/', create, name='create'),
    path('<int:post_id>/detail', detail, name='detail'),
    path('<int:post_id>/update', update, name='update'),
    path('<int:post_id>/delete', delete, name='delete'),
    path('mymong_ty/', mymong_ty, name="mymong_ty"),
    path('mymong_te/', mymong_te, name="mymong_te"),
    path('mymong_sy/', mymong_sy, name="mymong_sy"),
    path('mymong_se/', mymong_se, name="mymong_se"),
    path('manage/', manage, name="manage"),
]