# Generated by Django 4.0 on 2021-12-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='nationality',
            field=models.CharField(choices=[('TY', '태양인'), ('TE', '태음인'), ('SY', '소양인'), ('SE', '소음인')], max_length=2, null=True, verbose_name='nationality'),
        ),
    ]
