# Generated by Django 4.0 on 2021-12-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('cal', models.IntegerField()),
                ('walk', models.IntegerField()),
                ('hour', models.IntegerField()),
                ('min', models.IntegerField()),
            ],
        ),
    ]
