# Generated by Django 4.0 on 2021-12-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='hour',
            field=models.IntegerField(blank=True),
        ),
    ]
