# Generated by Django 4.0 on 2021-12-24 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_users_nationality'),
        ('mongapp', '0003_alter_record_cal_alter_record_hour_alter_record_min_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MongUser',
            new_name='Mongs',
        ),
        migrations.AddField(
            model_name='record',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.users', verbose_name='현유저'),
        ),
    ]
