# Generated by Django 3.2.3 on 2021-12-25 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mongapp', '0004_rename_monguser_mongs_record_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='walk',
            field=models.CharField(choices=[('0', '0보 이상'), ('1000', '1000보 이상'), ('2000', '2000보 이상'), ('3000', '3000보 이상'), ('4000', '4000보 이상'), ('5000', '5000보 이상'), ('6000', '6000보 이상'), ('7000', '7000보 이상'), ('8000', '8000보 이상'), ('9000', '9000보 이상'), ('10000', '10000보 이상')], max_length=10000, null=True, verbose_name='walk'),
        ),
    ]
